#!/bin/bash
# Script for uninstall cageframework tools

# ----- CAGE COUNCIL -----

#

clear

echo "

";

if [ "$PREFIX" = "/data/data/com.termux/files/usr" ]; then

    INSTALL_DIR="$PREFIX/usr/share/doc/cageframework"

    BIN_DIR="$PREFIX/bin/"

    BASH_PATH="$PREFIX/bin/bash"

    TERMUX=true

elif [ "$(uname)" = "cage" ]; then

    INSTALL_DIR="/usr/local/cageframework"

    BIN_DIR="/usr/local/bin/"

    BASH_PATH="/bin/bash"

    TERMUX=false

else

    INSTALL_DIR="$HOME/.cageframework"

    BIN_DIR="/usr/local/bin/"

    BASH_PATH="/bin/bash"

    TERMUX=false

fi

echo "[✔] Checking directories...";

if [ -d "$INSTALL_DIR" ]; then

        rm -rf "$INSTALL_DIR"

        rm "$BIN_DIR/cageframework*"

        sudo rm -rf "$INSTALL_DIR"

        sudo rm "$BIN_DIR/cageframework*"

    else

        echo "[✘] If you want to uninstall you must remove previous installations [✘] ";

        echo "[✘] Failed! [✘] ";

fi

echo "[✔] Cleaning up old directories...";

if [ -d "$ETC_DIR/cage" ]; then

    echo "$DIR_FOUND_TEXT"

    if [ "$TERMUX" = true ]; then

        rm -rf "$ETC_DIR/cage"

    else

        sudo rm -rf "$ETC_DIR/cage"

    fi

fi

clear

clear

echo "[✔] all good!"
